name: Run Bot
on:
  schedule:
    - cron: "0 */2 * * *"  # هر ۲ ساعت
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Download sing-box
        run: |
          wget -O sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.12.19/sing-box-1.12.19-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          chmod +x sing-box-1.12.19-linux-amd64/sing-box

      - name: Run bot
        run: python run_once.py
        env:
          SINGBOX_PATH: ${{ github.workspace }}/sing-box-1.12.19-linux-amd64/sing-box
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          SUBSCRIPTIONS_FILE: subscriptions.txt
